language: python
python:
    - "2.6"
    - "2.7"

notifications:
  email:
    - hanno@hannosch.eu
    - pycassa.maintainer@gmail.com

services:
    - cassandra

before_script:
  # give some more time for Cassandra to finish startup and actually test it
  - sleep 10
  - sudo service cassandra status

install:
    - python setup.py develop

script:
    - nosetests -v
